# Generated by Django 4.1.3 on 2023-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(default='images/default.png', upload_to='static\\images'),
        ),
    ]
