# Generated by Django 4.1.3 on 2023-04-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='image_main',
        ),
    ]
