# Generated by Django 4.1.3 on 2023-04-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_image_productimage_image_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_main',
        ),
    ]
