# Generated by Django 4.1.3 on 2023-04-02 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_image_product_image_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_main',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_main',
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
