# Generated by Django 4.1.3 on 2023-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_image_main_productimage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='static\\images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
