# Generated by Django 4.1.3 on 2023-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='images/default.png', upload_to='static\\images')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
    ]
