# Generated by Django 4.1.3 on 2023-04-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_category_image_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='name',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
    ]
