# Generated by Django 5.1.7 on 2025-04-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_categoryimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='image_type',
            field=models.CharField(choices=[('header', 'Header'), ('thumbnail', 'Thumbnail')], default='thumbnail', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(default='category_images/default.png', upload_to='category_images/'),
        ),
    ]
