# Generated by Django 5.1.7 on 2025-04-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_categoryimage_image_type_alter_categoryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('header', 'Header'), ('thumbnail', 'Thumbnail')], default='', max_length=10, null=True),
        ),
    ]
