# Generated by Django 5.1.7 on 2025-04-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='product',
        ),
        migrations.AlterField(
            model_name='productoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='productoption',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.productoptiongroup'),
        ),
    ]
