# Generated by Django 5.1.7 on 2025-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_review_stars_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('thumbnail', 'Thumbnail'), ('gallery', 'Gallery')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='product_images/default.png', upload_to='product_images/'),
        ),
    ]
