# Generated by Django 4.1.3 on 2023-04-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_main'),
        ('cart', '0002_product_remove_cart_items_remove_cart_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
